name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: debian:trixie
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-26.04-arm
            arch: arm64
          - os: ubuntu-26.04
            arch: x64

    steps:
      - uses: actions/checkout@v7
      - run: apt-get update && apt-get install -y g++ cmake ninja-build libcec-dev
      - run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - run: cp build/pitv pitv-${{ matrix.arch }}
      - uses: actions/upload-artifact@v7
        with:
          path: pitv-${{ matrix.arch }}
          archive: false